CREATE USER admin IDENTIFIED BY admin;
GRANT CONNECT, RESOURCE, DBA TO admin;
GRANT UNLIMITED TABLESPACE TO admin;
GRANT CREATE SESSION TO admin;
GRANT SELECT on v_$session TO admin;
GRANT SELECT on v_$process TO admin
